In [6]:
import pandas as pd

In [10]:
df = pd.read_excel('/Users/hqhyy/Library/Mobile Documents/com~apple~CloudDocs/PSC/app/output/log_2025-06-02.xlsx')
df

,id,timestamp,severity,message,label,data_extracted
0,683d04817aeae77418f3f90c,2025-06-02 01:55:13.108000+00:00,warning,"WebAPI Long Running Request: ""/api/v1.0/AppLan...",PERFORMANCE_WARNING,"{'request_info': '""/api/v1.0/AppLanguageResour..."
1,683d04817aeae77418f3f90d,2025-06-02 01:55:13.163000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."
2,683d13747aeae77418f3f90e,2025-06-02 02:59:00.212000+00:00,warning,"WebAPI Long Running Request: ""/api/Authenticat...",PERFORMANCE_WARNING,"{'request_info': '""/api/Authentications/LoginM..."
3,683d13747aeae77418f3f90f,2025-06-02 02:59:00.262000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."
4,683d18557aeae77418f3f910,2025-06-02 03:19:49.900000+00:00,warning,"WebAPI Long Running Request: ""/api/Authenticat...",PERFORMANCE_WARNING,"{'request_info': '""/api/Authentications/LoginM..."
5,683d18567aeae77418f3f911,2025-06-02 03:19:49.929000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."

In [11]:
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

In [12]:
df

,id,timestamp,severity,message,label,data_extracted
0,683d04817aeae77418f3f90c,2025-06-02 01:55:13.108000+00:00,warning,"WebAPI Long Running Request: ""/api/v1.0/AppLan...",PERFORMANCE_WARNING,"{'request_info': '""/api/v1.0/AppLanguageResour..."
1,683d04817aeae77418f3f90d,2025-06-02 01:55:13.163000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."
2,683d13747aeae77418f3f90e,2025-06-02 02:59:00.212000+00:00,warning,"WebAPI Long Running Request: ""/api/Authenticat...",PERFORMANCE_WARNING,"{'request_info': '""/api/Authentications/LoginM..."
3,683d13747aeae77418f3f90f,2025-06-02 02:59:00.262000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."
4,683d18557aeae77418f3f910,2025-06-02 03:19:49.900000+00:00,warning,"WebAPI Long Running Request: ""/api/Authenticat...",PERFORMANCE_WARNING,"{'request_info': '""/api/Authentications/LoginM..."
5,683d18567aeae77418f3f911,2025-06-02 03:19:49.929000+00:00,information,"WebAPI Request: ""PostRequest"" null LogAction {...",API_REQUEST,"{'request_info': '""PostRequest"" null', 'log_ac..."